### ISSUE TITLE
exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by mcrot** [codestation/go-s3-backup#1]
First of all, thanks for this handy tool! I've used your docker image 'postgres-s3-backup' for a while and it was quite useful.

Now, with the image 'go-s3-backup' I've got a problem. I run this in Docker swarm with definition in a compose file
and I only get the message 
```
standard_init_linux.go:228: exec user process caused: no such file or directory
``` 
My setup looks like this:

Excerpt from the compose file:

```yaml
 dbbackup:
    build:
      context: .
      dockerfile: ./compose/production/dbbackup/Dockerfile
    image: localhost:5000/production_dbbackup
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    entrypoint: /entrypoint
    deploy:
      placement:
        constraints:
          - node.role==manager
```

Dockerfile:
```Dockerfile
FROM codestation/go-s3-backup

ARG RESTORE_DATABASE=0
ENV RESTORE_DATABASE=$RESTORE_DATABASE
# Set RESTORE_DATABASE to 1 in environment in order to restore
# the database.

COPY ./compose/production/dbbackup/entrypoint /entrypoint
RUN sed -i 's/\r//' /entrypoint
RUN chmod +x /entrypoint
```

`entrypoint` file:
```sh
#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_USER="${POSTGRES_USER}"
export DATABASE_PASSWORD="${POSTGRES_PASSWORD}"
export DATABASE_NAME="${POSTGRES_DB}"
export DATABASE_HOST="${POSTGRES_HOST}"
export DATABASE_PORT="${POSTGRES_PORT}"

export S3_ENDPOINT="${AWS_S3_ENDPOINT_URL}"
export S3_BUCKET="${AWS_STORAGE_BUCKET_NAME}"

export MAX_BACKUPS=10
export S3_REGION="eu-central-1"
export S3_PREFIX="backup/"
export S3_FORCE_PATH_STYLE=1

if [ $RESTORE_DATABASE -eq 1 ]
then
    echo "Dropping old database, restoring last dump.."
    exec /bin/go-s3-backup restore postgres --postgres-drop s3
else
    export SCHEDULE=${DBBACKUP_SCHEDULE}

    echo "Starting backup schedule ${SCHEDULE}.."
    exec /bin/go-s3-backup backup postgres s3
fi
```

Practically the same files worked with docker-compose and with image `codestation/postgres-s3-backup`
without problems. Now I want to use Docker Swarm and your current image `codestation/go-s3-backup`.

How can I find out which file or directory is meant in this error message:
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```
